addons:
  browserstack:
    username: ${BROWSERSTACK_USERNAME}
    access_key: ${BROWSERSTACK_ACCESS_KEY}
    forcelocal: true
language: node_js
node_js:
  - 12
  - 14
  - 16
cache:
  directories:
    - node_modules
stages:
  - test
  - name: browserstack
    if: fork IS false
jobs:
  include:
    - stage: browserstack
      node_js: '14'
      script: grunt browserstack
